version: "3"
services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    networks:
      - fitO2-network

  web:
    build: .
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails db:create && bundle exec rails db:migrate && bundle exec rails db:seed && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app_name
    ports:
      - "3000:3000"
    networks:
      - fitO2-network
networks:
  fitO2-network:
